import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import VideoPlayer from '@/components/VideoPlayer'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const [src, setSrc] = useState('/vids/new');
  const router = useRouter();
  const query = router.query;
  const seq = query.seq;

  useEffect(() => {
    if (typeof seq === 'string') {
      setSrc(`/api/gen-manifest?seq=${seq}`);
    }
  }, [seq]);

  const [src, setSrc] = useState('/api/gen-manifest');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <VideoPlayer src={src}></VideoPlayer>
      </main>
    </>
  )
}
